site_name: AI for Humanity
site_url: https://jon-chun.github.io

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link

nav:
  - Home: index.md
  - Research: research.md
  - Resources: resources.md
  - Courses: courses.md
  - Social Media: socialmedia.md
  - About: about.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascript/extra.js
